JohnLCaron/netchdf

- src/main/kotlin/com/sunya/cdm/api/DataType.kt
- src/main/kotlin/com/sunya/netchdf/hdf5/DataObject.kt
- src/main/kotlin/com/sunya/netchdf/hdf5/FractalHeap.kt
- src/main/kotlin/com/sunya/netchdf/hdf5/H5builder.kt
- src/main/kotlin/com/sunya/netchdf/hdf5/H5reader.kt
- src/main/kotlin/com/sunya/netchdf/hdf5/MessageHeader.kt
- src/main/kotlin/com/sunya/netchdf/hdf5/SharedMessage.kt
- src/test/kotlin/com/sunya/netchdf/hdf5/H5headerTest.kt
add shared messages, vlen atts, opaque atts
> Finish pass1 hdf5/netcdf4 headers

- src/main/kotlin/com/sunya/cdm/api/Netcdf.kt
- src/main/kotlin/com/sunya/cdm/iosp/OpenFile.kt
- src/main/kotlin/com/sunya/cdm/iosp/StructureData.kt
- src/main/kotlin/com/sunya/netchdf/hdf5/CdmBuilder.kt
- src/main/kotlin/com/sunya/netchdf/hdf5/H5reader.kt
- src/main/kotlin/com/sunya/netchdf/hdf5/Hdf5File.kt
- src/main/kotlin/com/sunya/netchdf/hdf5/MessageDataType.kt
- src/main/kotlin/com/sunya/netchdf/hdf5/MessageHeader.kt
- src/main/kotlin/com/sunya/netchdf/netcdf3/N3header.kt
- src/main/kotlin/com/sunya/netchdf/netcdf3/Netcdf3File.kt
- src/main/kotlin/com/sunya/netchdf/netcdf4/NetchdfFile.kt
- src/main/kotlin/com/sunya/netchdf/netcdfClib/NCheader.kt
- src/main/kotlin/com/sunya/netchdf/netcdfClib/NetcdfClibFile.kt
- src/main/kotlin/com/sunya/netchdf/netcdfClib/UserTypes.kt
- src/test/kotlin/com/sunya/netchdf/NetchdfCompare.kt
- src/test/kotlin/com/sunya/netchdf/hdf5/H5headerCompare.kt
- src/test/kotlin/com/sunya/netchdf/hdf5/H5headerTest.kt
- src/test/kotlin/com/sunya/netchdf/netcdf3/N3dataCompare.kt
- src/test/kotlin/com/sunya/netchdf/netcdf3/N3headerCompare.kt
- src/test/kotlin/com/sunya/netchdf/netcdf3/N3headerTest.kt
- src/test/kotlin/com/sunya/netchdf/netcdf3/N3readTest.kt
- src/test/kotlin/com/sunya/netchdf/netcdf4/N4dataTest.kt
- src/test/kotlin/com/sunya/netchdf/netcdf4/N4strictTest.kt
add Closeable
nested strings in compounds
h5: non-scalar chars become strings, add unlimited
> netchdf can handle netcdf3, netcdf4, hdf5

- Readme.md
- src/main/kotlin/com/sunya/cdm/api/Cdl.kt
- src/main/kotlin/com/sunya/cdm/api/Dimension.kt
- src/main/kotlin/com/sunya/cdm/api/Typedef.kt
- src/main/kotlin/com/sunya/cdm/iosp/LayoutRegular.kt
- src/main/kotlin/com/sunya/cdm/iosp/StructureData.kt
- src/main/kotlin/com/sunya/netchdf/hdf5/CdmBuilder.kt
- src/main/kotlin/com/sunya/netchdf/hdf5/DataObject.kt
- src/main/kotlin/com/sunya/netchdf/hdf5/H5builder.kt
- src/main/kotlin/com/sunya/netchdf/hdf5/H5reader.kt
- src/main/kotlin/com/sunya/netchdf/hdf5/Hdf5File.kt
- src/main/kotlin/com/sunya/netchdf/hdf5/MessageDataType.kt
- src/main/kotlin/com/sunya/netchdf/hdf5/MessageHeader.kt
- src/main/kotlin/com/sunya/netchdf/hdf5/SharedObjects.kt
- src/main/kotlin/com/sunya/netchdf/netcdf3/Netcdf3File.kt
- src/main/kotlin/com/sunya/netchdf/netcdf4/Netcdf4.kt
- src/main/kotlin/com/sunya/netchdf/netcdfClib/NCheader.kt
- src/main/kotlin/com/sunya/netchdf/netcdfClib/NetcdfClibFile.kt
- src/main/kotlin/com/sunya/netchdf/netcdfClib/UserTypes.kt
- src/test/kotlin/com/sunya/netchdf/NetchdfCompare.kt
- src/test/kotlin/com/sunya/netchdf/hdf5/H5headerCompare.kt
fix various discrepencies between h5 and nclib
> compound fields can have arrays

- src/main/kotlin/com/sunya/cdm/api/Datatype.kt
- src/main/kotlin/com/sunya/cdm/api/Range.kt
- src/main/kotlin/com/sunya/cdm/array/ArrayTyped.kt
- src/main/kotlin/com/sunya/cdm/array/ArrayVlen.kt
- src/main/kotlin/com/sunya/cdm/array/StructureData.kt
- src/main/kotlin/com/sunya/netchdf/hdf5/CdmBuilder.kt
- src/main/kotlin/com/sunya/netchdf/hdf5/H5Group.kt
- src/main/kotlin/com/sunya/netchdf/hdf5/Hdf5File.kt
- src/main/kotlin/com/sunya/netchdf/netcdf3/N3header.kt
- src/main/kotlin/com/sunya/netchdf/netcdf3/Netcdf3File.kt
- src/main/kotlin/com/sunya/netchdf/netcdf4/NetchdfFile.kt
- src/main/kotlin/com/sunya/netchdf/netcdf4/NetchdfFileFormat.kt
- src/main/kotlin/com/sunya/netchdf/netcdfClib/NCheader.kt
- src/main/kotlin/com/sunya/netchdf/netcdfClib/NetcdfClibFile.kt
- src/test/kotlin/com/sunya/netchdf/hdf5/H5dataCompare.kt
- src/test/kotlin/com/sunya/netchdf/hdf5/H5headerTest.kt
fix compare Vlen, Compound data
> Support nested typedefs in HDF5

- Readme.md
> docs: typo

- Readme.md
- src/main/kotlin/com/sunya/cdm/api/Dimension.kt
- src/main/kotlin/com/sunya/cdm/api/Group.kt
- src/main/kotlin/com/sunya/netchdf/hdf4/H4builder.kt
- src/main/kotlin/com/sunya/netchdf/hdf4/Tag.kt
- src/main/kotlin/com/sunya/netchdf/hdf4Clib/HCheader.kt
- src/main/kotlin/com/sunya/netchdf/hdf4Clib/Hdf4ClibFile.kt
- src/main/kotlin/com/sunya/netchdf/parser/CdlParser.kt
- src/main/kotlin/com/sunya/netchdf/parser/NetcdfCdl.kt
- src/test/kotlin/com/sunya/netchdf/cdl/CdlParseTest.kt
- src/test/kotlin/com/sunya/netchdf/cdl/CdlReadAndParseTest.kt
- src/test/kotlin/com/sunya/netchdf/hdf4/H4compareNc.kt
Dimension must clean up the name
> Explore finding stuff though the HDF4 C API

- src/main/kotlin/com/sunya/cdm/api/Variable.kt
- src/main/kotlin/com/sunya/netchdf/hdf4/H4builder.kt
- src/main/kotlin/com/sunya/netchdf/hdf4/ODLparser.kt
- src/main/kotlin/com/sunya/netchdf/hdf4Clib/HCheader.kt
- src/main/kotlin/com/sunya/netchdf/parser/CdlParser.kt
- src/main/kotlin/com/sunya/netchdf/parser/OdlParser.kt
- src/test/kotlin/com/sunya/netchdf/parser/CdlParseTest.kt
- src/test/kotlin/com/sunya/netchdf/parser/CdlReadAndParseTest.kt
- src/test/kotlin/com/sunya/netchdf/parser/OdlParseTest.kt
appears to be non-optional to get the group structure, which is not in the SD API.
> Use structMetadata in HC, pass 1

- src/main/kotlin/com/sunya/cdm/api/Cdl.kt
- src/main/kotlin/com/sunya/cdm/api/Group.kt
- src/main/kotlin/com/sunya/cdm/api/Variable.kt
- src/main/kotlin/com/sunya/netchdf/hdf4/H4builder.kt
- src/main/kotlin/com/sunya/netchdf/hdf4/ODLparser.kt
- src/main/kotlin/com/sunya/netchdf/hdf4/TagEnum.kt
- src/main/kotlin/com/sunya/netchdf/hdf4Clib/HCheader.kt
- src/main/kotlin/com/sunya/netchdf/hdf5/H5CdmBuild.kt
- src/main/kotlin/com/sunya/netchdf/netcdfClib/NCheader.kt
- src/main/kotlin/com/sunya/netchdf/parser/CdlParser.kt
- src/test/kotlin/com/sunya/netchdf/NetchdfTest.kt
- src/test/kotlin/com/sunya/netchdf/hdf4/H4compareNc.kt
eos still core dumps on malloc, likely Vattrinfo2/Vgetattr2
> N4 and HC agree, except for eos

- clibs/src/test/kotlin/com/sunya/netchdf/NetchdfTest.kt
- core/src/main/kotlin/com/sunya/cdm/api/Cdl.kt
- core/src/main/kotlin/com/sunya/cdm/api/Range.kt
- core/src/main/kotlin/com/sunya/cdm/api/Section.kt
- core/src/main/kotlin/com/sunya/cdm/util/Escaping.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf4/H4builder.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf4/H4tiledData.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf4/LayoutSegmented.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf4/Vinfo.kt
- core/src/main/kotlin/com/sunya/netchdf/netcdf3/N3header.kt
- core/src/main/kotlin/com/sunya/netchdf/netcdf3/Netcdf3File.kt
> Try to simplify Section and Range.

- clibs/src/test/kotlin/com/sunya/netchdf/hdf4Clib/Hdf4ClibFile.kt
- clibs/src/test/kotlin/com/sunya/netchdf/netcdfClib/NetcdfClibFile.kt
- core/src/main/kotlin/com/sunya/cdm/api/Netchdf.kt
- core/src/main/kotlin/com/sunya/cdm/layout/Chunker.kt
- core/src/main/kotlin/com/sunya/cdm/layout/Layout.kt
- core/src/main/kotlin/com/sunya/cdm/layout/LayoutRegular.kt
- core/src/main/kotlin/com/sunya/cdm/layout/LayoutRegularSegmented.kt
- core/src/main/kotlin/com/sunya/cdm/layout/TransferChunk.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf4/H4chunkReader.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf4/Hdf4File.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf4/LayoutSegmented.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf5/H5chunkIterator.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf5/H5chunkReader.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf5/H5reader.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf5/Hdf5File.kt
- core/src/main/kotlin/com/sunya/netchdf/netcdf3/Netcdf3File.kt
- core/src/test/kotlin/com/sunya/cdm/layout/TestMaxChunkSize.kt
Annotate layout and chunking code.
> Refactor H5 data reading to eliminate duplicate code.

- clibs/src/test/kotlin/com/sunya/netchdf/NetchdfClibTest.kt
- core/build.gradle.kts
- core/src/main/kotlin/com/sunya/cdm/layout/Chunker.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf4/H4builder.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf4/H4chunkIterator.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf4/H4chunkReader.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf4/H4tiledData.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf4/Hdf4File.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf5/H5chunkIterator.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf5/H5chunkReader.kt
- core/src/test/kotlin/com/sunya/netchdf/NetchdfTest.kt
- core/src/test/kotlin/com/sunya/netchdf/TestFiles.kt
- core/src/test/kotlin/com/sunya/netchdf/hdf4/H4readTest.kt
- core/src/test/kotlin/com/sunya/netchdf/hdf5/H5readTest.kt
Move pure read tests back to core module, so they can be run in parallel.
> Add H4ChunkIterator

- Readme.md
- clibs/src/test/kotlin/com/sunya/netchdf/NetchdfExtra.kt
- clibs/src/test/kotlin/com/sunya/netchdf/hdf4/H4compareHC.kt
- clibs/src/test/kotlin/com/sunya/netchdf/hdf4/TestFiles.kt
- clibs/src/test/kotlin/com/sunya/netchdf/hdf4Clib/HCheader.kt
- clibs/src/test/kotlin/com/sunya/netchdf/hdf4Clib/Hdf4ClibFile.kt
- core/build.gradle.kts
- core/src/main/kotlin/com/sunya/cdm/array/ArrayStructureData.kt
- core/src/main/kotlin/com/sunya/cdm/iosp/OpenFile.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf4/H4builder.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf4/Hdf4File.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf4/Special.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf4/Tag.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf4/TagEnum.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf4/Vinfo.kt
- core/src/test/kotlin/com/sunya/netchdf/hdf4/H4readTest.kt
HClib still seeing memory corruption.
Improve reading ArrayStructure data.
Reorganize hdf4 test files.
> Fix problems reading hdf4 files

- clibs/src/test/kotlin/com/sunya/netchdf/NetchdfClibTest.kt
- clibs/src/test/kotlin/com/sunya/netchdf/hdf4/HCcompare.kt
- clibs/src/test/kotlin/com/sunya/netchdf/hdf4/HCeosCompare.kt
- clibs/src/test/kotlin/com/sunya/netchdf/hdf4Clib/HCheader.kt
- clibs/src/test/kotlin/com/sunya/netchdf/hdf4Clib/HClibFile.kt
- core/src/main/kotlin/com/sunya/cdm/api/Cdl.kt
- core/src/main/kotlin/com/sunya/cdm/array/ArrayByte.kt
- core/src/main/kotlin/com/sunya/cdm/array/ArrayDouble.kt
- core/src/main/kotlin/com/sunya/cdm/array/ArrayFloat.kt
- core/src/main/kotlin/com/sunya/cdm/array/ArrayInt.kt
- core/src/main/kotlin/com/sunya/cdm/array/ArrayLong.kt
- core/src/main/kotlin/com/sunya/cdm/array/ArrayShort.kt
- core/src/main/kotlin/com/sunya/cdm/array/ArrayStructureData.kt
- core/src/main/kotlin/com/sunya/cdm/array/ArrayTyped.kt
- core/src/main/kotlin/com/sunya/cdm/iosp/OpenFile.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf4/H4builder.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf4/Hdf4File.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf4/ODLparser.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf4/Tag.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf4/Vinfo.kt
- core/src/test/kotlin/com/sunya/netchdf/NetchdfTest.kt
- core/src/test/kotlin/com/sunya/netchdf/hdf4/H4readTest.kt
Find _FillValue attributes; dont use "defaults".
ArrayTyped.equals()
distinguish hdf4 and hdf4-eos
Concat multiple structMetadata strings.
cdl: varname:attname -> :attname
> Fix problems reading data from hdf4 files

- Readme.md
- clibs/src/main/kotlin/com/sunya/netchdf/hdf5Clib/H5CTypeInfo.kt
- clibs/src/main/kotlin/com/sunya/netchdf/hdf5Clib/H5Cbuilder.kt
- clibs/src/test/kotlin/com/sunya/netchdf/hdf5Clib/H5CopenTest.kt
- core/src/main/kotlin/com/sunya/cdm/api/Cdl.kt
- core/src/main/kotlin/com/sunya/cdm/api/Datatype.kt
- core/src/main/kotlin/com/sunya/cdm/api/Group.kt
- core/src/main/kotlin/com/sunya/cdm/api/Section.kt
- core/src/main/kotlin/com/sunya/cdm/api/Variable.kt
- core/src/main/kotlin/com/sunya/cdm/layout/Chunker.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf5/H5TypeInfo.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf5/H5builder.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf5/H5cdmBuilder.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf5/H5reader.kt
- core/src/main/kotlin/com/sunya/netchdf/netcdf4/Netcdf4.kt
- testdata/src/main/kotlin/com/sunya/testdata/H5CFiles.kt
Add Datatype.REFERENCE. 
Implement attributes that are reference types. Port to H5.
Stop using kotlin "and/or" operator
> Add HDF5 clib, pass 3.

- clibs/src/main/kotlin/com/sunya/netchdf/hdf4Clib/HCbuilder.kt
- clibs/src/main/kotlin/com/sunya/netchdf/hdf5Clib/H5CTypeInfo.kt
- clibs/src/main/kotlin/com/sunya/netchdf/hdf5Clib/H5Cbuilder.kt
- clibs/src/main/kotlin/com/sunya/netchdf/hdf5Clib/Hdf5ClibFile.kt
- clibs/src/test/kotlin/com/sunya/netchdf/NetchdfClibTest.kt
- clibs/src/test/kotlin/com/sunya/netchdf/hdf5Clib/H5CopenTest.kt
- clibs/src/test/kotlin/com/sunya/netchdf/netcdf3/N3dataCompare.kt
- core/src/main/kotlin/com/sunya/cdm/api/Datatype.kt
- core/src/main/kotlin/com/sunya/cdm/api/Typedef.kt
- core/src/main/kotlin/com/sunya/cdm/array/ArrayStructureData.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf4/H4builder.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf5/H5cdmBuilder.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf5/H5reader.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf5/H5typedef.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf5/Hdf5File.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf5/Heap.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf5/MessageDataLayout.kt
- testdata/src/main/kotlin/com/sunya/testdata/H5CFiles.kt
H5 can read compact data.
Fix promoted attributes in H5, H5C.
Add endian field to StructureMember.
> H5C can read data.

- Readme.md
- clibs/src/main/kotlin/com/sunya/netchdf/hdf5Clib/H5CTypeInfo.kt
- clibs/src/main/kotlin/com/sunya/netchdf/hdf5Clib/H5Cbuilder.kt
- clibs/src/main/kotlin/com/sunya/netchdf/netcdfClib/NCheader.kt
- clibs/src/main/kotlin/com/sunya/netchdf/netcdfClib/NetcdfClibFile.kt
- clibs/src/main/kotlin/com/sunya/netchdf/netcdfClib/UserTypes.kt
- clibs/src/test/kotlin/com/sunya/netchdf/hdf5Clib/H5CopenTest.kt
- core/src/main/kotlin/com/sunya/cdm/api/Datatype.kt
- core/src/main/kotlin/com/sunya/cdm/array/ArrayStructureData.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf5/H5TypeInfo.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf5/H5reader.kt
Datatype.STRING.withVlen to distinguish fixed length and var length strings.
sdataArray.putStringsOnHeap() lamda needs member
> Vlen strings

- Readme.md
- clibs/src/test/kotlin/com/sunya/netchdf/NetchdfClibTest.kt
- clibs/src/test/kotlin/com/sunya/netchdf/hdf4/HCcompare.kt
- clibs/src/test/kotlin/com/sunya/netchdf/netcdf3/N3dataCompare.kt
- clibs/src/test/kotlin/com/sunya/netchdf/netcdf3/N3headerCompare.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf4/ODLparser.kt
- core/src/main/kotlin/com/sunya/netchdf/netcdf3/N3header.kt
- core/src/test/kotlin/com/sunya/netchdf/NetchdfTest.kt
- testdata/src/main/kotlin/com/sunya/testdata/N4Files.kt
- testdata/src/main/kotlin/com/sunya/testdata/SortFiles.kt
Fix Netcdf3 "bug CDM-52".
ODLparser bails out if dimension length == 0
> Cleanup test data, remove duplicates.

- clibs/src/main/kotlin/com/sunya/netchdf/hdf4Clib/H4Cbuilder.kt
- clibs/src/main/kotlin/com/sunya/netchdf/hdf5Clib/H5Cbuilder.kt
- core/src/main/kotlin/com/sunya/cdm/api/Attribute.kt
- core/src/main/kotlin/com/sunya/cdm/api/Group.kt
- core/src/main/kotlin/com/sunya/cdm/api/Variable.kt
- core/src/main/kotlin/com/sunya/cdm/util/CdmFullNames.kt
- core/src/main/kotlin/com/sunya/cdm/util/Escaping.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf4/ODLparser.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf5/H5builder.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf5/H5cdmBuilder.kt
- core/src/test/kotlin/com/sunya/cdm/api/TestGroup.kt
- core/src/test/kotlin/com/sunya/cdm/util/TestCdmFullNames.kt
Add Group tests.
Add Excaping.backslashEscape()
Variable.Builder.dimList -> dimNames
> Add CdmFullNames and tests.

- clibs/src/main/kotlin/com/sunya/netchdf/hdf4Clib/H4Cbuilder.kt
- clibs/src/main/kotlin/com/sunya/netchdf/hdf4Clib/H4ClibFile.kt
- clibs/src/test/kotlin/com/sunya/netchdf/NetchdfClibTest.kt
- core/src/test/kotlin/com/sunya/netchdf/NetchdfTest.kt
- core/src/test/kotlin/com/sunya/netchdf/hdf4/H4readTest.kt
reduce max bytes read 10 10M to make things faster and avoid OME.
> hdf4 readGRdata() flip shape dimensions.

- Readme.md
- clibs/src/main/kotlin/com/sunya/netchdf/hdf5Clib/H5Cbuilder.kt
- clibs/src/main/kotlin/com/sunya/netchdf/hdf5Clib/H5ClibFile.kt
- clibs/src/main/kotlin/com/sunya/netchdf/netcdfClib/NClibFile.kt
- core/src/main/kotlin/com/sunya/cdm/api/Datatype.kt
- core/src/main/kotlin/com/sunya/cdm/array/ArrayOpaque.kt
- core/src/main/kotlin/com/sunya/cdm/array/ArrayString.kt
- core/src/main/kotlin/com/sunya/cdm/array/ArrayStructureData.kt
- core/src/main/kotlin/com/sunya/cdm/array/ArrayVlen.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf5/H5chunkReader.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf5/H5reader.kt
- core/src/test/kotlin/com/sunya/cdm/array/TestArrayStructureData.kt
- core/src/test/kotlin/com/sunya/cdm/array/TestArrayVlen.kt
Iterator is over Array\<T>, not T.
Add tests for ArrayVlen.
Datatype.values().
> ArrayVLen is generic, add ArrayVlen.fromArray()

- .idea/statistic.xml
- Readme.md
- core/src/main/kotlin/com/sunya/cdm/api/Datatype.kt
- core/src/main/kotlin/com/sunya/cdm/array/ArrayStructureData.kt
- core/src/main/kotlin/com/sunya/cdm/array/ArrayTyped.kt
- core/src/main/kotlin/com/sunya/cdm/array/ArrayVlen.kt
- core/src/main/kotlin/com/sunya/cdm/array/StructureMember.kt
- core/src/test/kotlin/com/sunya/cdm/array/TestArrayStructureData.kt
- core/src/test/kotlin/com/sunya/cdm/array/TestArrayTyped.kt
- core/src/test/kotlin/com/sunya/cdm/array/TestArrayVlen.kt
Split StructureMember from ArrayStructureData
> Tests for ArrayVlen, ArrayStructureData.

- Readme.md
- clibs/src/main/kotlin/com/sunya/netchdf/hdf5Clib/H5CTypeInfo.kt
- clibs/src/main/kotlin/com/sunya/netchdf/netcdfClib/NCheader.kt
- clibs/src/main/kotlin/com/sunya/netchdf/netcdfClib/NClibFile.kt
- clibs/src/test/kotlin/com/sunya/netchdf/NetchdfClibTest.kt
- clibs/src/test/kotlin/com/sunya/netchdf/hdf5/Hdf5Compare.kt
- clibs/src/test/kotlin/com/sunya/netchdf/netcdf3/N3dataCompare.kt
- core/build.gradle.kts
- core/src/main/kotlin/com/sunya/cdm/api/Datatype.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf5/H5cdmBuilder.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf5/H5reader.kt
- core/src/main/kotlin/com/sunya/netchdf/netcdf3/N3builder.kt
- core/src/main/kotlin/com/sunya/netchdf/netcdf3/Netcdf3File.kt
- core/src/test/kotlin/com/sunya/cdm/api/TestAttribute.kt
- core/src/test/kotlin/com/sunya/netchdf/NetchdfTest.kt
- core/src/test/kotlin/com/sunya/netchdf/hdf5/H5enumTest.kt
- core/src/test/kotlin/com/sunya/netchdf/hdf5/H5readTest.kt
- core/src/test/kotlin/com/sunya/netchdf/netcdf3/N3charTest.kt
- core/src/test/kotlin/com/sunya/netchdf/netcdf4/N4charTest.kt
> CHAR Variable returns UByte.

- clibs/src/main/java/com/sunya/netchdf/netcdfClib/ffm/nc_vlen_t.java
- clibs/src/main/kotlin/com/sunya/netchdf/hdf4Clib/H4ClibFile.kt
- clibs/src/main/kotlin/com/sunya/netchdf/hdf5Clib/H5Cbuilder.kt
- clibs/src/main/kotlin/com/sunya/netchdf/hdf5Clib/H5ClibFile.kt
- clibs/src/main/kotlin/com/sunya/netchdf/netcdfClib/NCheader.kt
- clibs/src/main/kotlin/com/sunya/netchdf/netcdfClib/NClibFile.kt
- clibs/src/main/kotlin/com/sunya/netchdf/netcdfClib/UserTypes.kt
- clibs/src/test/c/readVlenFloat.c
- clibs/src/test/kotlin/com/sunya/netchdf/NetchdfClibExtra.kt
- clibs/src/test/kotlin/com/sunya/netchdf/NetchdfClibTest.kt
- clibs/src/test/kotlin/com/sunya/netchdf/hdf5/H5dataTiming.kt
- clibs/src/test/kotlin/com/sunya/netchdf/hdf5Clib/H5CopenTest.kt
- clibs/src/test/kotlin/com/sunya/netchdf/netcdf4/N4versionTest.kt
- clibs/src/test/kotlin/com/sunya/netchdf/netcdf4/VlenFillValueTest.kt
- clibs/testStatus.txt
- core/src/main/kotlin/com/sunya/cdm/api/Section.kt
- core/src/main/kotlin/com/sunya/cdm/array/StructureMember.kt
- core/src/test/kotlin/com/sunya/netchdf/NetchdfTest.kt
- testdata/src/main/kotlin/com/sunya/testdata/H5CFiles.kt
Fix netcdf4 FFI readCompoundAttValues, readAttributeValues, readArray Data when reading string data.
Fix h5 FFI readVlenStrings, processCompoundData when reading string data.
Fix reading vlen data in NcLibFile, readVlenDataList.
> Fix FFI pointer errors

- Readme.md
- build.gradle.kts
- cli/build.gradle.kts
- clibs/build.gradle.kts
- clibs/src/main/kotlin/com/sunya/netchdf/netcdfClib/NCheader.kt
- clibs/testStatus.txt
- core/build.gradle.kts
- core/src/main/kotlin/com/sunya/cdm/api/Attribute.kt
- core/src/main/kotlin/com/sunya/cdm/api/Netchdf.kt
- core/src/main/kotlin/com/sunya/cdm/api/Section.kt
- core/src/main/kotlin/com/sunya/cdm/array/ArrayVlen.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf5/DataObject.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf5/H5builder.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf5/H5group.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf5/H5typedef.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf5/Hdf5File.kt
- core/src/main/kotlin/com/sunya/netchdf/hdf5/MessageDataType.kt
- core/testStatus.txt
eliminate a few TODOs
allow public access in some places for netchdf-viewer. 
group = "com.sunya.netchdf"
> kotest.scan.disable

- core/src/commonMain/kotlin/com/sunya/netchdf/hdf5/ChunkedDataLayoutMessageV4.kt
- core/src/commonMain/kotlin/com/sunya/netchdf/hdf5/ExtensibleArrayIndex.kt
- core/src/commonMain/kotlin/com/sunya/netchdf/hdf5/H5chunkReader.kt
- core/src/commonMain/kotlin/com/sunya/netchdf/hdf5/Hdf5File.kt
- testfiles/src/test/kotlin/com/sunya/netchdf/JhdfReadTest.kt
readChunkedData() for all version4 chunked data.
> ExtensibleArrayIndex

- gradle/libs.versions.toml
> bump version tag to 0.5.0

- .idea/artifacts/netchdf_0_5_0.xml
- core/src/commonMain/kotlin/com/sunya/netchdf/hdf5/FilterPipeline.kt
- core/src/commonMain/kotlin/com/sunya/netchdf/hdf5/H5builder.kt
- core/src/commonMain/kotlin/com/sunya/netchdf/hdf5/MessageDataType.kt
- gradle/libs.versions.toml
- testfiles/build.gradle.kts
- testfiles/src/test/kotlin/com/sunya/netchdf/jhdf/JhdfCompare.kt
- testfiles/src/test/resources/logback.xml
> Jhdf data Compare

- cli/src/main/kotlin/com/sunya/netchdf/hdf5/BitShuffleFilter.kt
- core/src/commonMain/kotlin/com/sunya/cdm/api/Typedef.kt
- core/src/commonMain/kotlin/com/sunya/cdm/array/ArrayStructureData.kt
- core/src/commonMain/kotlin/com/sunya/cdm/array/StructureMember.kt
- core/src/commonMain/kotlin/com/sunya/netchdf/hdf5/H5builder.kt
- core/src/commonMain/kotlin/com/sunya/netchdf/hdf5/H5cdmBuilder.kt
- core/src/commonMain/kotlin/com/sunya/netchdf/hdf5/H5typedef.kt
- core/src/commonMain/kotlin/com/sunya/netchdf/hdf5/MessageDataType.kt
- core/src/commonTest/kotlin/com/sunya/cdm/api/TestTypedef.kt
- testfiles/src/test/kotlin/com/sunya/netchdf/JhdfReadTest.kt
- testfiles/src/test/kotlin/com/sunya/netchdf/jhdf/JhdfCompare.kt
redo convertEnums
improve StructureData.memberValues, StructureMember.value() 
register nested private typedefs
lots of work on JhdfCompare
> fix bitshuffle filter
